import jsPDF from "jspdf";
import { db } from "@/lib/db";
import { v4 as uuidv4 } from "uuid";
import crypto from "crypto";
import {
  getSOC2Controls,
  getOWASPMapping,
  getNISTMapping,
} from "@/lib/compliance-frameworks";

/* ── Types ── */

interface ReportFinding {
  code: string;
  severity: string;
  status: string;
  title: string;
  category: string;
  firstDetectedAt: Date | null;
  resolvedAt: Date | null;
}

interface ReportApp {
  name: string;
  url: string;
  status: string;
  score: number;
  findings: ReportFinding[];
  scanCount: number;
  lastScanAt: Date | null;
}

type Framework = "soc2" | "iso27001" | "nist";

/* ── Control Mapping ── */

const CONTROL_MAP: Record<string, Record<Framework, string>> = {
  "Headers": {
    soc2: "CC6.6 System Boundaries",
    iso27001: "A.14.1 Secure Development",
    nist: "PR.IP Info Protection",
  },
  "SSL/TLS": {
    soc2: "CC6.1 Logical Access",
    iso27001: "A.14.1 Secure Development",
    nist: "PR.IP Info Protection",
  },
  "Vulnerabilities": {
    soc2: "CC7.1 Monitoring",
    iso27001: "A.12.6 Vulnerability Mgmt",
    nist: "DE.CM Monitoring",
  },
  "Authentication": {
    soc2: "CC6.1 Logical Access",
    iso27001: "A.14.1 Secure Development",
    nist: "PR.IP Info Protection",
  },
  "Content Security": {
    soc2: "CC6.6 System Boundaries",
    iso27001: "A.14.1 Secure Development",
    nist: "PR.IP Info Protection",
  },
  "Monitoring": {
    soc2: "CC7.1 Monitoring",
    iso27001: "A.12.6 Vulnerability Mgmt",
    nist: "DE.CM Monitoring",
  },
  "Compliance": {
    soc2: "CC7.1 Monitoring",
    iso27001: "A.18.1 Compliance",
    nist: "ID.RA Risk Assessment",
  },
  "Access Control": {
    soc2: "CC6.1 Logical Access",
    iso27001: "A.14.1 Secure Development",
    nist: "ID.RA Risk Assessment",
  },
};

const FRAMEWORK_LABELS: Record<Framework, string> = {
  soc2: "SOC 2 Type II",
  iso27001: "ISO 27001:2022",
  nist: "NIST CSF 2.0",
};

/* ── Helpers ── */

function calcScore(findings: { severity: string }[]): number {
  let s = 100;
  for (const f of findings) {
    if (f.severity === "CRITICAL") s -= 25;
    else if (f.severity === "HIGH") s -= 10;
    else if (f.severity === "MEDIUM") s -= 3;
    else s -= 1;
  }
  return Math.max(0, s);
}

function fmtDate(d: Date): string {
  return d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function fmtShortDate(d: Date | null): string {
  if (!d) return "N/A";
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

/* ── PDF Primitives ── */

class ReportBuilder {
  doc: jsPDF;
  y: number = 20;
  readonly pageW = 210;
  readonly marginL = 14;
  readonly marginR = 196;
  readonly footerY = 288;

  constructor() {
    this.doc = new jsPDF();
  }

  checkPage(need: number) {
    if (this.y + need > 270) {
      this.doc.addPage();
      this.y = 20;
    }
  }

  newPage() {
    this.doc.addPage();
    this.y = 20;
  }

  heading(text: string, size = 16) {
    this.checkPage(12);
    this.doc.setFontSize(size);
    this.doc.setFont("helvetica", "bold");
    this.doc.text(text, this.marginL, this.y);
    this.y += size * 0.6;
  }

  body(text: string, indent = 0) {
    this.doc.setFontSize(10);
    this.doc.setFont("helvetica", "normal");
    const lines = this.doc.splitTextToSize(text, this.marginR - this.marginL - indent);
    for (const line of lines) {
      this.checkPage(6);
      this.doc.text(line, this.marginL + indent, this.y);
      this.y += 5;
    }
  }

  bullet(text: string, indent = 4) {
    this.body(`• ${text}`, indent);
  }

  gap(px = 6) {
    this.y += px;
  }

  separator() {
    this.checkPage(8);
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(this.marginL, this.y, this.marginR, this.y);
    this.y += 6;
  }

  tableRow(cols: string[], widths: number[], bold = false) {
    this.checkPage(7);
    this.doc.setFontSize(9);
    this.doc.setFont("helvetica", bold ? "bold" : "normal");
    let x = this.marginL;
    for (let i = 0; i < cols.length; i++) {
      this.doc.text(cols[i], x, this.y);
      x += widths[i];
    }
    this.y += 5;
  }

  addFooters(orgId: string, reportHash: string, timestamp: string, reportId: string) {
    const pageCount = this.doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(7);
      this.doc.setFont("helvetica", "normal");
      this.doc.setTextColor(120, 120, 120);
      this.doc.text(
        `Generated by Scantient | Confidential | Page ${i} of ${pageCount}`,
        this.pageW / 2,
        this.footerY,
        { align: "center" },
      );
      this.doc.text(
        `Report ID: ${reportId}`,
        this.pageW / 2,
        this.footerY + 4,
        { align: "center" },
      );
      this.doc.setTextColor(0, 0, 0);
    }
  }

  toBuffer(): Buffer {
    return Buffer.from(this.doc.output("arraybuffer"));
  }
}

/* ── Data Loading ── */

async function loadReportData(orgId: string, from?: Date, to?: Date) {
  const dateFilter = from && to ? { startedAt: { gte: from, lte: to } } : {};

  const apps = await db.monitoredApp.findMany({
    where: { orgId },
    include: {
      monitorRuns: {
        where: dateFilter,
        orderBy: { startedAt: "desc" },
        include: { findings: true },
      },
    },
  });

  const org = await db.organization.findUnique({
    where: { id: orgId },
    select: { name: true },
  });

  const reportApps: ReportApp[] = apps.map((app) => {
    const allFindings = app.monitorRuns.flatMap((r) => r.findings);
    return {
      name: app.name,
      url: app.url,
      status: app.status,
      score: calcScore(allFindings),
      findings: allFindings.map((f) => ({
        code: f.code,
        severity: f.severity,
        status: f.status,
        title: f.title,
        category: (f as Record<string, unknown>).category as string ?? "Vulnerabilities",
        firstDetectedAt: f.createdAt ?? null,
        resolvedAt: f.resolvedAt ?? null,
      })),
      scanCount: app.monitorRuns.length,
      lastScanAt: app.monitorRuns[0]?.startedAt ?? null,
    };
  });

  return { orgName: org?.name ?? "Organization", reportApps };
}

/* ── Main Report Generator ── */

export async function generateComplianceReport(
  orgId: string,
  options?: { from?: Date; to?: Date; framework?: Framework },
): Promise<Buffer> {
  const from = options?.from;
  const to = options?.to ?? new Date();
  const framework = options?.framework;
  const { orgName, reportApps } = await loadReportData(orgId, from, to);

  const now = new Date();
  const reportId = uuidv4();
  const rb = new ReportBuilder();
  const doc = rb.doc;

  // ── Cover Page ──
  rb.y = 80;
  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.text("Scantient Security", rb.pageW / 2, rb.y, { align: "center" });
  rb.y += 12;
  doc.text("Compliance Report", rb.pageW / 2, rb.y, { align: "center" });
  rb.y += 20;

  doc.setFontSize(14);
  doc.setFont("helvetica", "normal");
  doc.text(orgName, rb.pageW / 2, rb.y, { align: "center" });
  rb.y += 10;

  doc.setFontSize(11);
  const dateRange = from
    ? `${fmtDate(from)} – ${fmtDate(to)}`
    : `As of ${fmtDate(now)}`;
  doc.text(dateRange, rb.pageW / 2, rb.y, { align: "center" });
  rb.y += 8;

  if (framework) {
    doc.text(`Framework: ${FRAMEWORK_LABELS[framework]}`, rb.pageW / 2, rb.y, { align: "center" });
    rb.y += 8;
  }

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Report ID: ${reportId}`, rb.pageW / 2, rb.y + 20, { align: "center" });
  doc.setTextColor(0, 0, 0);

  // ── Executive Summary ──
  rb.newPage();
  rb.heading("Executive Summary", 18);
  rb.gap(4);

  const totalFindings = reportApps.reduce((s, a) => s + a.findings.length, 0);
  const openFindings = reportApps.reduce((s, a) => s + a.findings.filter((f) => f.status === "OPEN").length, 0);
  const resolvedFindings = totalFindings - openFindings;
  const criticalCount = reportApps.reduce((s, a) => s + a.findings.filter((f) => f.severity === "CRITICAL").length, 0);
  const highCount = reportApps.reduce((s, a) => s + a.findings.filter((f) => f.severity === "HIGH").length, 0);
  const mediumCount = reportApps.reduce((s, a) => s + a.findings.filter((f) => f.severity === "MEDIUM").length, 0);
  const lowCount = totalFindings - criticalCount - highCount - mediumCount;
  const avgScore = reportApps.length
    ? Math.round(reportApps.reduce((s, a) => s + a.score, 0) / reportApps.length)
    : 0;

  rb.bullet(`Portfolio security score: ${avgScore}/100`);
  rb.bullet(`Total applications monitored: ${reportApps.length}`);
  rb.bullet(`Total findings: ${totalFindings} (${openFindings} open, ${resolvedFindings} resolved)`);
  rb.bullet(`Findings by severity: ${criticalCount} Critical, ${highCount} High, ${mediumCount} Medium, ${lowCount} Low`);
  rb.bullet(`Total scans in period: ${reportApps.reduce((s, a) => s + a.scanCount, 0)}`);
  rb.gap(8);

  // ── Per-App Sections ──
  rb.heading("Per-Application Security Posture", 18);
  rb.gap(4);

  for (const app of reportApps) {
    rb.checkPage(35);
    rb.heading(`${app.name}`, 13);
    rb.body(`URL: ${app.url}`);
    rb.body(`Security Score: ${app.score}/100 | Status: ${app.status}`);
    rb.body(`Scans: ${app.scanCount} | Last scan: ${fmtShortDate(app.lastScanAt)}`);
    rb.gap(2);

    const appCrit = app.findings.filter((f) => f.severity === "CRITICAL").length;
    const appHigh = app.findings.filter((f) => f.severity === "HIGH").length;
    const appMed = app.findings.filter((f) => f.severity === "MEDIUM").length;
    const appLow = app.findings.length - appCrit - appHigh - appMed;
    rb.body(`Findings: ${appCrit} Critical, ${appHigh} High, ${appMed} Medium, ${appLow} Low`, 4);

    if (app.findings.length > 0) {
      rb.gap(2);
      const widths = [65, 25, 25, 67];
      rb.tableRow(["Finding", "Severity", "Status", "Detected"], widths, true);
      for (const f of app.findings.slice(0, 15)) {
        rb.tableRow(
          [
            f.title.substring(0, 35),
            f.severity,
            f.status,
            fmtShortDate(f.firstDetectedAt),
          ],
          widths,
        );
      }
      if (app.findings.length > 15) {
        rb.body(`... and ${app.findings.length - 15} more findings`, 4);
      }
    }
    rb.gap(6);
    rb.separator();
  }

  // ── Remediation Status ──
  rb.checkPage(40);
  rb.heading("Remediation Status", 18);
  rb.gap(4);
  rb.bullet(`Open findings: ${openFindings}`);
  rb.bullet(`Resolved findings: ${resolvedFindings}`);

  // Mean time to remediate
  const resolvedWithDates = reportApps.flatMap((a) =>
    a.findings.filter((f) => f.resolvedAt && f.firstDetectedAt),
  );
  if (resolvedWithDates.length > 0) {
    const totalDays = resolvedWithDates.reduce((s, f) => {
      const diff = (f.resolvedAt!.getTime() - f.firstDetectedAt!.getTime()) / (1000 * 60 * 60 * 24);
      return s + diff;
    }, 0);
    const mttr = Math.round(totalDays / resolvedWithDates.length);
    rb.bullet(`Mean time to remediate: ${mttr} days`);
  } else {
    rb.bullet("Mean time to remediate: N/A (insufficient data)");
  }

  // SLA compliance (30-day SLA for critical, 90-day for others)
  const overdueFindings = reportApps.flatMap((a) =>
    a.findings.filter((f) => {
      if (f.status !== "OPEN" || !f.firstDetectedAt) return false;
      const ageDays = (now.getTime() - f.firstDetectedAt.getTime()) / (1000 * 60 * 60 * 24);
      return f.severity === "CRITICAL" ? ageDays > 30 : ageDays > 90;
    }),
  );
  const slaCompliance = openFindings > 0
    ? Math.round(((openFindings - overdueFindings.length) / openFindings) * 100)
    : 100;
  rb.bullet(`SLA compliance: ${slaCompliance}% (${overdueFindings.length} overdue findings)`);
  rb.gap(8);

  // ── Control Mapping Table ──
  rb.checkPage(40);
  rb.heading("Compliance Control Mapping", 18);
  rb.gap(4);

  const frameworks: Framework[] = framework ? [framework] : ["soc2", "iso27001", "nist"];
  for (const fw of frameworks) {
    rb.heading(FRAMEWORK_LABELS[fw], 13);
    rb.gap(2);
    const colWidths = [40, 50, 50, 42];
    rb.tableRow(["Check Category", "Control", "Findings", "Status"], colWidths, true);

    for (const [category, mapping] of Object.entries(CONTROL_MAP)) {
      const catFindings = reportApps.flatMap((a) =>
        a.findings.filter((f) => f.category === category),
      );
      const openCount = catFindings.filter((f) => f.status === "OPEN").length;
      const status = catFindings.length === 0 ? "No data" : openCount === 0 ? "Compliant" : `${openCount} open`;
      rb.tableRow([category, mapping[fw], `${catFindings.length}`, status], colWidths);
    }
    rb.gap(6);
  }

  // ── OWASP Top 10 Section ──
  rb.newPage();
  rb.heading("OWASP Top 10 (2021) Mapping", 18);
  rb.gap(4);
  rb.body("Each finding is mapped to the relevant OWASP Top 10 2021 risk category.");
  rb.gap(4);

  const allOpenFindings = reportApps.flatMap((a) =>
    a.findings
      .filter((f) => f.status === "OPEN")
      .map((f) => ({ code: f.code, title: f.title, severity: f.severity })),
  );
  const owaspResults = getOWASPMapping(allOpenFindings);
  const owaspWidths = [15, 70, 50, 42];
  rb.tableRow(["ID", "Category", "Description", "Status"], owaspWidths, true);
  for (const cat of owaspResults) {
    const desc = cat.category.description.substring(0, 45);
    rb.tableRow([cat.categoryId, cat.category.name, desc, cat.status === "pass" ? "Compliant" : `${cat.violatingFindings.length} finding(s)`], owaspWidths);
  }
  rb.gap(8);

  // ── NIST CSF Section ──
  rb.heading("NIST CSF 2.0 Mapping", 18);
  rb.gap(4);
  rb.body("Findings mapped to NIST Cybersecurity Framework 2.0 functions.");
  rb.gap(4);
  const nistResults = getNISTMapping(allOpenFindings);
  const nistWidths = [15, 35, 100, 37];
  rb.tableRow(["ID", "Function", "Description", "Status"], nistWidths, true);
  for (const fn of nistResults) {
    rb.tableRow([fn.functionId, fn.function.name, fn.function.description.substring(0, 55), fn.status === "pass" ? "Compliant" : `${fn.violatingFindings.length} finding(s)`], nistWidths);
  }
  rb.gap(8);

  // ── SOC 2 Summary ──
  rb.heading("SOC 2 Trust Services Criteria Summary", 18);
  rb.gap(4);
  const soc2Results = getSOC2Controls(allOpenFindings);
  const soc2Widths = [20, 75, 42, 50];
  rb.tableRow(["Control", "Name", "Category", "Status"], soc2Widths, true);
  for (const ctrl of soc2Results) {
    rb.tableRow([ctrl.controlId, ctrl.control.name, ctrl.control.category, ctrl.status === "pass" ? "Compliant" : `${ctrl.violatingFindings.length} finding(s)`], soc2Widths);
  }
  rb.gap(8);

  // ── Evidence Section ──
  rb.newPage();
  rb.heading("Evidence: Timestamped Scan Results", 18);
  rb.gap(4);

  for (const app of reportApps) {
    if (app.findings.length === 0) continue;
    rb.checkPage(20);
    rb.heading(app.name, 12);
    const widths = [55, 20, 18, 45, 44];
    rb.tableRow(["Finding", "Severity", "Status", "First Detected", "Resolved"], widths, true);
    for (const f of app.findings.slice(0, 25)) {
      rb.tableRow(
        [
          f.title.substring(0, 30),
          f.severity,
          f.status,
          fmtShortDate(f.firstDetectedAt),
          fmtShortDate(f.resolvedAt),
        ],
        widths,
      );
    }
    if (app.findings.length > 25) {
      rb.body(`... and ${app.findings.length - 25} more findings`, 4);
    }
    rb.gap(6);
  }

  // ── Digital Signature Block ──
  rb.newPage();
  rb.heading("Digital Signature & Integrity", 18);
  rb.gap(8);

  const timestamp = now.toISOString();
  // Generate hash of report content for tamper evidence
  const contentForHash = JSON.stringify({
    reportId,
    orgId,
    timestamp,
    appCount: reportApps.length,
    totalFindings,
    avgScore,
  });
  const reportHash = crypto.createHash("sha256").update(contentForHash).digest("hex");

  rb.body(`Report ID: ${reportId}`);
  rb.body(`Organization ID: ${orgId}`);
  rb.body(`Generation Timestamp: ${timestamp}`);
  rb.body(`Report SHA-256 Hash: ${reportHash}`);
  rb.gap(8);
  rb.body("This hash can be used to verify the report has not been tampered with.");
  rb.body("Any modification to the report content will produce a different hash value.");
  rb.gap(12);
  rb.separator();
  rb.gap(4);
  rb.body("Authorized Signature: _______________________________");
  rb.gap(8);
  rb.body("Date: _______________________________");

  // ── Footers ──
  rb.addFooters(orgId, reportHash, timestamp, reportId);

  return rb.toBuffer();
}

/* ── Evidence Pack (framework-specific) ── */

export async function generateEvidencePack(
  orgId: string,
  framework: Framework,
  from: Date,
  to: Date,
): Promise<Buffer> {
  return generateComplianceReport(orgId, { from, to, framework });
}
